version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: kindo
      POSTGRES_PASSWORD: kindo_local
      POSTGRES_DB: kindo_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 